//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DB.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE InventarioMateriaPrima (
        ///	IdMateriaPrima INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
        ///    Descripcion VARCHAR(255),
        ///    Entradas INT DEFAULT 0,
        ///    Salidas INT DEFAULT 0,
        ///    StockActual INT DEFAULT 0,
        ///    UnidadMedida VARCHAR(50));
        ///GO
        ///
        ///CREATE TABLE Recetas (
        ///	IdReceta INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
        ///    NombreReceta VARCHAR(255),
        ///    Descripcion VARCHAR(500));
        ///GO
        ///
        ///CREATE TABLE RecetasDetalle (
        ///	IdReceta INT NOT NULL FOREIGN KEY REFERENCES Recetas(IdReceta),
        ///    IdMateriaPrima INT NOT NULL  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BD_Pasteleria_DDL {
            get {
                return ResourceManager.GetString("BD_Pasteleria_DDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Materia prima */
        ///-- Select
        ///Create or Alter Procedure SelectInventarioMateriaPrimaById
        ///    @IdMateriaPrima INT
        ///AS
        ///BEGIN
        ///    SELECT IdMateriaPrima, Descripcion, Entradas, Salidas, StockActual, UnidadMedida
        ///    FROM InventarioMateriaPrima
        ///    WHERE IdMateriaPrima = @IdMateriaPrima;
        ///END;
        ///GO
        ///
        ///--SelectAll
        ///Create or Alter Procedure SelectAllInventarioMateriaPrima
        ///AS
        ///BEGIN
        ///    SELECT IdMateriaPrima, Descripcion, Entradas, Salidas, StockActual, UnidadMedida
        ///    FROM InventarioMateriaPrima;
        ///END;
        ///GO
        ///
        ///- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BD_Pasteleria_DML {
            get {
                return ResourceManager.GetString("BD_Pasteleria_DML", resourceCulture);
            }
        }
    }
}
